vim.loader.enable()
-- require("vim._extui").enable({})

require("config_options")
require("config_plugins")
require("config_replace")
require("config_clipboard")
require("config_autoload")
require("config_keymaps")
require("config_codeautomation")
require("config_note")
require("config_worktrees")
-- require("config_monorepo")
