font_family      CaskaydiaMono NF Regular
# font_family      Lilex NFM
# font_family      Maple Mono NF Bold
# font_family      Monospace Argon Bold
# font_family      CaskaydiaMono NF SemiLight
bold_font        auto
italic_font      auto
bold_italic_font auto
# font_size        12
# font_size        17
font_size        16
# font_size        20
# modify_font cell_width 100%
modify_font cell_width 95%
modify_font cell_height 3px
modify_font underline_position 2px
tab_bar_style hidden
map f5 select_tab
foreground #F2F3F3
# background #1e2030
background #24283b

#color0 #6272a4
#color1 #EA708E
#color2 #88c0d0
#color3 #ebcb8b
#color4 #5A84E5
#color5 #C2A4FF
#color6 #61AFEF
#color7 #F2F3F3
#color8 #6272a4
#color9 #EA708E
#color10 #88c0d0
#color11 #ebcb8b
#color12 #5A84E5
#color13 #C2A4FF
#color14 #61AFEF
#color15 #F2F3F3

# Nord Colorscheme for Kitty
# Based on:
# - https://gist.github.com/marcusramberg/64010234c95a93d953e8c79fdaf94192
# - https://github.com/arcticicestudio/nord-hyper

foreground            #D8DEE9
#background            #2E3440
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #c8ccd4

# black
color0   #3B4252
color8   #3B4252

# red
color1   #ea708e
color9   #ea708e
#color1   #ea708e
#color9   #ea708e

# green
color2   #88d4c1
color10  #88d4c1

# yellow
color3   #EBCB8B
color11  #EBCB8B

# blue
color4  #7a88bd
color12 #7a88bd
#color4  #6272a4
#color12 #6272a4

# magenta
color5   #c2a4ff
color13  #c2a4ff

# cyan
color6   #b4d2f0
color14  #b4d2f0

# white
color7   #f2f3f3
color15  #f2f3f3


window_margin_width 3
confirm_os_window_close 0
close_on_child_death yes
allow_remote_control yes
shell_integration enabled
listen_on unix:/tmp/kitty

map f1 launch --type=tab fish -c ~/repos/scripts/kitty_new_tab.fish
map f3 launch --type=tab ~/repos/scripts/run.fish
# map f6 launch --type=overlay fish -c ~/repos/scripts/lastpass.fish
# map f8 launch --type=overlay fish -c ~/repos/scripts/accents.fish
map ctrl+; launch --type=overlay --allow-remote-control fish -c ~/repos/scripts/kitty_fuzzytabs.fish
map ctrl+y goto_tab 0
map ctrl+shift+u remote_control scroll-window 0.5p-
map ctrl+shift+d remote_control scroll-window 0.5p+
map ctrl+shift+a load_config_file

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten ~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim --nvim-args --clean -c "set clipboard=unnamedplus" --noplugin -n
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output --nvim-args --clean -c "set clipboard=unnamedplus" --noplugin -n
# Show clicked command output in nvim
# mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

cursor_trail 1
cursor_trail_start_threshold 20


# BEGIN_KITTY_FONTS
#font_family      family="Lilex Nerd Font Mono"
#bold_font        auto
#italic_font      auto
#bold_italic_font auto
# END_KITTY_FONTS
