$font = SF Pro Display Bold

general {
    fail_timeout = 700
    hide_cursor = true
}

background {
    monitor =
    path = ~/wallpapers/mountain.jpg
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 1
}

# Date
label {
    position = -100, -50
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds

    font_size = 30
    font_family = $font
    color = rgba(216, 222, 233, 0.90)

    halign = right
    valign = top
}

# Time
label {
    position = -50, -80
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M:%S")</span>"
    color = rgba(216, 222, 233, 0.90)
    font_size = 100
    font_family = $font
    halign = right
    valign = top
}

# Password
input-field {
    position = 0, 0
    monitor =
    size = 280, 55
    outline_thickness = 2
    rounding = 20
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(216, 222, 233, 0.5)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fail_color = rgb(200, 200, 200)
    check_color = rgba(EBCB8Baa)
    fade_on_empty = true
    font_family = $font
    # fail_text = <i>Failed</i>
    fail_text = 
    placeholder_text = 
    hide_input = false
    halign = center
    valign = center
}

animations {
    enabled = yes

    # bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = bezIn, 0.5,0.0,1.0,1.2
    bezier = bezOut, 0.0,0.5,0.5,1.0
    bezier = fastStart, 0.18,0.89,0.62,0.52
    bezier = overshot, 0.05,0.9,0.1,1.05
    bezier = superOvershot, 0.05,0.9,0.1,1.3
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = softsnap, 0.4, 0, 0.2, 1

    # animation = windows, 1, 5, overshot, popin 80%
    animation = fadeIn, 1, 20, smoothIn, #popin 85%
    animation = fadeOut, 1, 10, smoothOut, #popin 85%
    # animation = windowsOut, 1, 3, overshot, popin 100%
    # animation = windowsMove, 0, 4, softsnap
    # animation = border, 1, 100, softsnap
    # animation = borderangle, 1, 8, default
    # animation = workspaces, 1, 2, softsnap, slidefade 50%
    #
    # # animation = fadeIn, 1, 4, smoothIn
    # # animation = fadeOut, 1, 4, smoothOut
    # animation = fadeSwitch, 1, 4, smoothIn
    # animation = fadeDim, 1, 2, smoothIn
    # animation = fadeShadow, 1, 3, superOvershot
}
