"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """[╭─](blue bold) $username\
$hostname\
$localip\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$c\
$deno\
$dotnet\
$elixir\
$erlang\
$golang\
$haskell\
$helm\
$lua\
$nodejs\
$ocaml\
$python\
$rust\
$terraform\
$zig\
$conda\
$memory_usage\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break[╰─](blue bold)\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character"""

[cmd_duration]
format = '[$duration](bold yellow) '
show_milliseconds = true
min_time = 0

[hostname]
ssh_symbol = '󰢹 '
format = '[$ssh_symbol$hostname]($style) '
style = 'blue'

[username]
format = '[$user]($style) '
style_user = 'purple'

[status]
style = 'fg:red'
symbol = '🔴 '
format = '[-\[$status\]]($style) '
map_symbol = true
disabled = false
