"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """$username\
$hostname\
$localip\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$c\
$deno\
$dotnet\
$elixir\
$erlang\
$golang\
$haskell\
$helm\
$lua\
$nodejs\
$ocaml\
$python\
$rust\
$terraform\
$zig\
$conda\
$memory_usage\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character"""

[cmd_duration]
format = '[$duration](bold yellow) '
